<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE socios [

<!ELEMENT socios (socio)*>
<!ELEMENT socio (clave, nombre, edad, numero)>
<!ELEMENT clave (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT numero (#PCDATA)>

]>

<socios>
    <socio>
        <clave>hY75Du</clave>
        <nombre>Ana</nombre>
        <edad>21</edad>
        <numero>598</numero>
    </socio>
    <socio>
        <clave>j432bN</clave>
        <nombre>Iker</nombre>
        <edad>19</edad>
    </socio>
</socios>