<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE escritores [
    <!ELEMENT escritores (escritores*)>
    <!ELEMENT escritor (nombre, nacimiento)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT nacimiento (#PCDATA)>
]>

<escritores>
    <escritor>
        <nombre>Mario</nombre>
        <nacimiento>28 de marzo</nacimiento>
    </escritor>
    <escritor>
        <nacimiento>12 de abril</nacimiento>
        <nombre>Milan Kundera</nombre>
    </escritor>
</escritores>